wandb_version: 1

learning_rates:
  desc: null
  value:
  - 0.013
  - 0.2
  - 0.3
  - 0.6
max_depths:
  desc: null
  value:
  - 3
  - 4
  - 5
  - 6
n_estimator:
  desc: null
  value:
  - 43
  - 100
  - 150
loss_functions:
  desc: null
  value:
  - deviance
subsamples:
  desc: null
  value:
  - 0.8
  - 1.0
min_samples_splits:
  desc: null
  value:
  - 2
  - 4
min_samples_leaf:
  desc: null
  value:
  - 1
  - 2
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707673179.58686
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
